#  __  __ _            __  __             _
# |  \/  (_)          |  \/  |           (_)
# | \  / |_ _ __   ___| \  / | __ _ _ __  _  __ _
# | |\/| | | '_ \ / _ \ |\/| |/ _` | '_ \| |/ _` |
# | |  | | | | | |  __/ |  | | (_| | | | | | (_| |
# |_|  |_|_|_| |_|\___|_|  |_|\__,_|_| |_|_|\__,_|
#
# Author: MineManiaUK Staff


# Clear Chat Lines
clear-chat-lines: 100

# In order of priority.
# The first one will have the most priority.
format:
  # This will have the permissions chat.default
  default:
    prefix: ""
    postfix: ""
